pipelines:
  - name: pipeline_go_center_tests
    steps:
      - name: exec_lhci
        type: Bash
        configuration:
          environmentVariables:
              LHCI_BUILD_CONTEXT__EXTERNAL_BUILD_URL: "$step_url"
              LHCI_BUILD_CONTEXT__CURRENT_BRANCH: "$res_go_lh_branchName"
          inputResources:
            - name: go_lh
          runtime:
            type: image
            image:
              custom:
                name: hemanthsridhar-docker-lhci-server-center.bintray.io/lhci
                tag: "2.0"
                autoPull: true        # default true; pulls image before runx
        execution:
          onStart:
            - echo "Executing LHCI in container for Go Center"
          onExecute:
            - cd $res_go_lh_resourcePath/
            - lhci autorun --config="./lhci-go.json" --collect.url="https://search.gocenter.io/stats"
          onComplete:
            - add_run_files .lighthouseci lhci_report
