pipelines:
  - name: pipeline_conan_center_tests
    steps:
      - name: exec_lhci
        type: Bash
        configuration:
          environmentVariables:
              LHCI_BUILD_CONTEXT__EXTERNAL_BUILD_URL: "$step_url"
              LHCI_BUILD_CONTEXT__CURRENT_BRANCH: "$res_conan_lh_branchName"
          inputResources:
            - name: conan_lh
          runtime:
            type: image
            image:
              custom:
                name: hemanthsridhar-docker-lhci-server-center.bintray.io/lhci
                tag: "4.0"
                autoPull: true        # default true; pulls image before runx
        execution:
          onStart:
            - echo "Executing LHCI in container for Conan"
          onExecute:
            - cd $res_conan_lh_resourcePath/
            - lhci autorun
          onComplete:
            - add_run_files .lighthouseci lhci_report
